### ISSUE TITLE
Javascript error on User guide and Examples

### ISSUE THREAD

**Issue by thohan88** [machow/reactable-py#21]
All rendered tables currently throws a javascript error for me on Chrome and Safari:
[📚 User guide](https://machow.github.io/reactable-py/get-started)
[🧩 Examples](https://machow.github.io/reactable-py/demos/)

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'ReactModel' from module '@widgetti/jupyter-react'
makeError@https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1:1804
onScriptError@https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js:1:17093
```

<img width="821" alt="image" src="https://github.com/user-attachments/assets/ff2189d3-bd0f-4d1e-9d18-8f3e77bcb04a">

**Comment by machow** [comment]
Shoot -- thanks for raising this. This should be fixed in v0.1.2. I've pinned reactable-py to not use the latest version of ipyreact, as its corresponding node library doesn't seem to be deployed (so ends up returning a 404 on the cdn it's pulling from).
