### ISSUE TITLE
Column default sort order does not override global default

### ISSUE THREAD

**Issue by dhimmel** [machow/reactable-py#25]
Amazing package! Extremely powerful and functional for its star count. I sense a bright future here.

Similar to [this example](https://machow.github.io/reactable-py/get-started/controls-sorting.html#default-sort-order) but without setting `default_sorted`:

```py
import reactable
from reactable.data import penguins
import polars as pl

reactable.embed_css()

pl_penguins = penguins.to_polars()
reactable.Reactable(
    pl_penguins,
    default_sort_order="desc",
    columns=[reactable.Column(id="species", default_sort_order="asc")],
)
```

The first time I click on the `species` header, that columns sorts descending (along with all other columns). The expected behavior is for `species` to first sort ascending because the Column sets `default_sort_order="asc"`.

Seems to work at https://glin.github.io/reactable/articles/examples.html#default-sort-order

**Comment by machow** [comment]
Hey @dhimmel, long time no see! Shoot, thanks for reporting -- it looks currently we handle the initial sort order, but need to add a Column.default_sort_desc property to say what should happen when resorting 😓

**Comment by dhimmel** [comment]
> long time no see!

haha yes! @trangdata told me about R reactable and then we saw you're making a python client.

> it looks currently we handle the initial sort order, but need to add a `Column.default_sort_desc` property to say what should happen when resorting

I figured `Column.default_sort_order` would control both the initial sorting for columns in `default_sorted` and then subsequent first sorting actions on columns not in `default_sorted`.

**Comment by machow** [comment]
> haha yes! @trangdata told me about R reactable and then we saw you're making a python client.

ah nice!

Sorry, I should have been clearer that it's a bug in reactable-py :/, but should be fixed in the v0.1.3 release just now!

**Comment by dhimmel** [comment]
Cool thanks for https://github.com/machow/reactable-py/pull/26. The following code using a `default_col_def` now does what I want, which is the first time you click on any column it sorts descending, except for species which sorts ascending on first click:

```py
pl_penguins = penguins.to_polars()
reactable.Reactable(
    pl_penguins,
    default_col_def=reactable.Column(default_sort_order="desc"),
    columns=[reactable.Column(id="species", default_sort_order="asc")],
)
```

I don't think the global `default_sort_order` method is working though in `v0.1.3` because columns other than `species` are not sorting descending upon first click:

```py
reactable.Reactable(
    pl_penguins,
    default_sort_order="desc",
    columns=[reactable.Column(id="species", default_sort_order="asc")],
)
```

Anyways, I'm all good since the `default_col_def` method is working!

**Comment by machow** [comment]
shoot :/, the table sorting default behavior should be fixed now in https://github.com/machow/reactable-py/releases/tag/v0.1.4

**Comment by dhimmel** [comment]
Confirming that both examples now work as expected. Thanks!
