### ISSUE TITLE
Should `great_tables` be a dependency (currently dev dependency)

### ISSUE THREAD

**Issue by dhimmel** [machow/reactable-py#29]
Just installing `reactable` without also install `great_tables` will result in

```
ModuleNotFoundError: No module named 'great_tables'
```

Due to:

https://github.com/machow/reactable-py/blob/d04e38a8397ccab0a906adbf5f3962f09dc92604/reactable/render_gt.py#L7-L12

Currently `great_tables` is only a dev dep:

https://github.com/machow/reactable-py/blob/d04e38a8397ccab0a906adbf5f3962f09dc92604/pyproject.toml#L63

**Comment by machow** [comment]
Closing, but definitely let me know if this isn't fixed in v0.1.5!
