### ISSUE TITLE
Make it possible to use reactable-py with pyodide and pycafe

### ISSUE THREAD

**Issue by MarcSkovMadsen** [machow/reactable-py#34]
If you try starting (a Panel project) on Py.CAFE with

**app.py**

```python
from reactable import CellInfo, Column, Reactable
```

**requirements.txt**

```bash
reactable
```

[Run on Py.Cafe](https://py.cafe/snippet/panel/v1?pycafe-app-view=false&pycafe-edit-enable=true#c=H4sIAO0_RWcEA41Su27DMAz8FYOzYiQp0gIe66Vds3RIMyg2XQuQJVWmkxqB_71U_UgNtHCg6XjHO5LQFTKbIyRQeFtFHmVG8qQxUpWznqIUtX41hRVRanVTGRHtR8m7AQEePxvlsUJDNZtM_UxR64KvkwY1Q9dSaU0otDZXOa7O63j7GG-Y0rK1DUFyhTP6WgXVlq2tpb29hPJg5RkJyEqlc48sOkwMZ9ZITF5UTiUkm91aQKXMWw8fevSC6qPknABVzm2F0vjMrjX61BqSyqD_JyFIV6deyxIngy9Ad-zEpJmm-MuAyVufdC52Lcx7b_Tvq8b0RfMYv3yG5dWHVZbWHjeeDTDFlIPr5ml3Tyah57LUS6GjLqSG14mf8_MHOxy7b4KzuxexAgAA)

You will see

![image](https://github.com/user-attachments/assets/b8bd0201-b142-4290-8582-9e81b7b9be95)

If you add `panel` to `requirements.txt` and restart python you will see

![image](https://github.com/user-attachments/assets/a963485b-ea36-4c07-98ca-d2735a7303a0)

I.e. there is a long way before its possible to run the examples in #33.

Please make it possible to use `reactable-py` in pyodide and Py.Cafe with Panel and other data app frameworks.

**Comment by maartenbreddels** [comment]
Thanks for sharing this!

[this will work](https://py.cafe/snippet/panel/v1?pycafe-app-view=false&pycafe-edit-enable=true#c=H4sIAAKRRWcEA51YTW_jNhD9K6r2agmy_BE7hS5dFGive-lhHQS0RFtMKJKhqNjyIv-9byRb3UURZHZvlj1v5s3M43Dkb3FpKxnfxwdvm8hLUQax1zJSjbM-RJ-l1n-bg51Fn63uGjOLvtxMdiaexV6-dMrLRprQwsmE35nOa632i51pX7QKEh-cMFIDE3pHAW-Prg-1NfRFbytVyeQ1S_N1OsdPWvS2C_H9t_hV-laRVY6Y1oYv9kRfX115PM3isla68hJGX6dfQKaVAT-eVBXq-H6-ymZxo8w_4-NifPpLqmONOPSoKsAOSss_4LWV_rM1QSgj_TsRyDTZj7YwcYL8xvHbw9tssuHwu1Igfu8Y_uddOJe6_scYv-bp-_6l4RzI5_deGcw_rua1Oh9V8lbEHwhMYeqr1_ndihMzSI-vhf4o6M1uTPzh7W02dBRi_voAAdrymR7JC0oE-09RLdr6PtqKPN8uq2wuhdxnmVhtF_lmn223q8VhvVmKnRGmh-iOMhRFlm7T-SL6PXJahIP1zWPbt0E2UVFEu_jPpi29cgiwiwHzR2vypDwcVLJXplLm2BZFPk_zNON4iD5FDVjDURuCfZaG0OkynXPAO4OzK8q6KHAAefEAQRQgFikwPEQpfVAHBWJZvkRiOROGmhTFPJ2vudTKWnjIJzEwE1pdpCeeC3ZAq60XjSjQwWW65oAiYaoIPz7eLEeTkzKLfHTZNOSOnzSkZzvveso851a4Ejg4okT7K4qWpUz1VbJExsGiTisogBlNnmXZBSiVpJZxUXVodLBWQ6AZtMNsqaoM-rFI75jmwz2GmyhpZBBUlqLYpCt2tAnuZYs2lBJs1xDDiol3_XAnFkiRfQYBoiuxANF8y2bqruMGBDdoHZPgk6xwptAzTCgmQpknkVML5lxVPXXISHot9snEcUFCYeK1Ms_q0CcqJHQOSGNMZCP8c2VPqCVbMTfILRoRZfaAoJ1rxUESSXYPGhGctoPKFOUKNGrD5lsNRBOnu6OiaU9KYw6XpsKaNkZjIkzXUFFgj1PAg2DRqwR4YeRxCznshhRlxQ-CQT1WnaljIFpbIPcNO4Y8O0lneYn7nJXJ_2-D38hEfmwyXRhOaW1PqAXdGaygwGCXdyGh4fqswJckvNwwsS0mOWq_Qo4syLRwuLY_YpMqSE78LmAP8xZjdRDuHS_Dd2r2U2XtvEzk60iXfRmP0kd2RBN3gx42ZxHwavJoRCNHjOtdf2XA8lmSFGk1AQ82keOwsw-Kv-PTH9-w6hBcMeTN7dJwISW4PuWojpxOQOpsG1gNGzxcAKN9jx3zVV0S2peQJSmYOfJd34sGFLFR8ENdmhewWwLCymfS_PTCW6Cc7IFPb12yHbu3YO_ZrToP6mOvSm3ABkhNGxbYNbeA2P6MqDAa2RM-vFSYvdiQ11wlBi9U0MMigD1zyabWO2yZiTzjmf4PABx6YlcwXMZi_IwMuzJpVOntsAsgEpfq9f8PajH7mJ1KrEcB71LD0WQGOsm9xFvC9UUxw5XJjTauYmY_lZOqCRkzA5_7C6bWqxp24qGkzFtxZy7KYQDhPYzduulfpLbVOxO__QsazDyiuBIAAA)

But ideally, this works more more like on a regular desktop, meaning we install sqlite by default, and we fix that error!

**Comment by MarcSkovMadsen** [comment]
It works perfect. Thanks.

https://py.cafe/awesome.panel.org/panel-reactable-table

![image](https://github.com/user-attachments/assets/4f383882-8585-49e3-82f2-2b03e2f958ba)
